
public enum Command
{
    NONE,
    SBEGIN = 0,
    S_PLAYER_ENTER,
    S_ITEM_SPAWN,
    S_CREATURE_SPAWN,
    S_PLAYER_ACTION,
    S_ENTITY_DESTORY,
    S_EXIT,

    SEND,

    CBEGIN,
    C_LOGIN,
    C_ENTER_SCENE_DONE,
    C_PLAYER_ACTION,

    CEND,

    DEBUGGING, // THE FOLLOWING MESSEGES ARE FOR DEBUGGING
    C_PATH_FINDING,
    S_PATH_FINDING,

    CMD_END, // DO NOT GREATER THAN UINT_MAX !!!
}

